title: Site options
pages:
  template:
    - over
    - fysiotherapie
    - extra
    - informatie

fields:
  title:
    label: Title
    type:  text

  description:
    label: Text
    type:  textarea
    buttons:

  address:
    label: Adres
    type: text
    icon: map-marker
    width: 1/2

  telephone: 
    label: Telefoonnumer
    type: text
    icon: phone
    width: 1/2

  email:
    label: Email adres
    type: email
    width: 1/2

  facebook:
    label: Facebook link
    type: url
    width: 1/2