title: Page

fields:
  title:
    label: Title
    type:  text

  description:
    label: Text
    type:  textarea
    buttons:

  address:
    label: Adres
    type: text
    icon: map-marker

  telephone: 
    label: Telefoonnumer
    type: text
    icon: phone

  email:
    label: Email adres
    type: email